language: node_js
sudo: false
before_install:
  - "export CODECLIMATE_REPO_TOKEN=d7abe4f421d4b39b0618b3f8d75d112e7e2d347837ad33e4a94b1be8ab57ccca"
install:
  - "npm install grunt-cli -g"
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
cache:
  directories:
   - 'node_modules'
