language: node_js
sudo: false
install:
  - "npm install grunt-cli -g"
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
cache:
  directories:
   - 'node_modules'
